### ISSUE TITLE
关于目录

### ISSUE THREAD

**Issue by InsHomePgup** [wangdoc/frontpage#11]
在阅读比较长的章节的时候,如果能有一个侧边栏可以切换目录的话我想是一个很不错的阅读体验......
![image](https://github.com/user-attachments/assets/f2b45660-1bf8-4d2d-8247-60bd48e72c66)
方便切换回去看到当前章节的其他内容

**Comment by ruanyf** [comment]
点击标题处的箭头，或者按下 home 键，可以回到文首。

**Comment by InsHomePgup** [comment]
嗯嗯,通过这两个方式也是蛮方便的 .我之前就是鼠标中键快速滚动到顶部再切换目录就有点累
